spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: newuser
      password: newuserpassword
      database: users
      authentication-database: admin

server:
  port: 8080

